<div align="center">

# 🐼 S14 — pandas aplicado al portafolio
### Lenguajes de Programación · Ingeniería Financiera

*De columnas sueltas a una tabla que se puede interrogar*

</div>

---

En S13 aprendimos NumPy: arrays, operaciones vectorizadas, funciones de estadística. Hoy conoceremos **pandas** — la librería que organiza datos de distinto tipo (texto, enteros, decimales) en una sola tabla con nombres.

| Bloque | Tema |
|:---:|---|
| 00 | ¿Qué es pandas y para qué se usa? |
| 01 | La estructura: Series y DataFrame |
| 02 | Cómo se importa pandas |
| 03 | Sintaxis básica: creación y exploración |
| 04 | Selección de datos |
| 05 | Operaciones más usadas |
| 06 | Todo junto: el portafolio como DataFrame |
| 07 | 🎯 Reto individual |

## 00 · ¿Qué es pandas y para qué se usa?

> **Nota** — Objetivo: entender qué problema resuelve pandas, y por qué lo aprendido en NumPy no es suficiente.

Un portafolio real no es solo números: tiene tickers (texto), cantidades (enteros), precios (decimales) y, más adelante, fechas. NumPy asume que todo el array es del mismo tipo — por eso necesitamos algo que junte columnas de distinto tipo en una sola tabla, con nombres. Eso es exactamente lo que resuelve **pandas**.

pandas es una librería que permite trabajar con datos organizados en tablas: leerlos, explorarlos, limpiarlos, filtrarlos y resumirlos. Está construida sobre NumPy — por dentro, cada columna de una tabla de pandas es un array.

> 💡 **Idea clave** — NumPy nos ayuda a calcular rápidamente sobre muchos números. Por otro lado, pandas nos permite organizar datos de distinto tipo en tablas que podemos leer, filtrar y consultar. Es importante destacar que no compiten, sino que pandas utiliza NumPy internamente.

📚 Fuente: ["Package overview", pandas.pydata.org](https://pandas.pydata.org/docs/getting_started/overview.html)

---
## 01 · La estructura: Series y DataFrame

> **Nota** — Objetivo: distinguir las dos estructuras de datos principales que ofrece pandas.

pandas nos ofrece dos tipos de estructuras:

- **Series** — un arreglo unidimensional etiquetado, capaz de contener datos de cualquier tipo. Es una sola columna, con índice.
- **DataFrame** — una estructura de dos dimensiones que guarda datos como una tabla, con filas y columnas. Cada columna de un DataFrame es, de hecho, una Series.

In [11]:
import numpy as np
import pandas as pd

precios = pd.Series([195, 385, 185, 165])
print(precios)
print(type(precios))

0    195
1    385
2    185
3    165
dtype: int64
<class 'pandas.core.series.Series'>

In [12]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio": [195, 385, 185, 165]
})
print(portafolio)
print(type(portafolio))

  ticker  cantidad  precio
0   AAPL        10     195
1   MSFT         8     385
2   AMZN        12     185
3  GOOGL         6     165
<class 'pandas.core.frame.DataFrame'>

📚 Fuente: ["10 minutes to pandas" — "Basic data structures in pandas", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#basic-data-structures-in-pandas)

---
## 02 · Cómo se importa pandas

> **Nota** — Objetivo: importar pandas correctamente, junto con NumPy.

In [13]:
import numpy as np
import pandas as pd

print("pandas", pd.__version__, "listo para usar.")

pandas 2.2.3 listo para usar.

La convención `as pd` es ampliamente utilizada en la comunidad. Raramente veremos `import pandas` sin este alias. pandas se importa comúnmente junto con NumPy, dado que lo utiliza internamente.

---
## 03 · Sintaxis básica: creación y exploración

> **Nota** — Objetivo: Crearemos un DataFrame desde cero y lo exploraremos antes de realizar cualquier cálculo.

Un DataFrame se crea a partir de un diccionario, donde cada clave se convierte en el nombre de una columna:

In [14]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio_compra": [180, 400, 170, 150],
    "precio_actual": [195, 385, 185, 165]
})

portafolio

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
1   MSFT         8            400            385
2   AMZN        12            170            185
3  GOOGL         6            150            165

**✏️ Completa el código** — Exploremos el DataFrame antes de cualquier cálculo, de manera similar a como exploramos los precios de Yahoo Finance en S13.

In [17]:
print(portafolio.head())     # primeras filas
print(portafolio.shape)       # (filas, columnas)
print(portafolio.dtypes)       # tipo de cada columna
print(portafolio.describe())     # resumen estadístico

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
1   MSFT         8            400            385
2   AMZN        12            170            185
3  GOOGL         6            150            165
(4, 4)
ticker           object
cantidad          int64
precio_compra     int64
precio_actual     int64
dtype: object
        cantidad  precio_compra  precio_actual
count   4.000000       4.000000       4.000000
mean    9.000000     225.000000     232.500000
std     2.581989     117.331439     102.428837
min     6.000000     150.000000     165.000000
25%     7.500000     165.000000     180.000000
50%     9.000000     175.000000     190.000000
75%    10.500000     235.000000     242.500000
max    12.000000     400.000000     385.000000

<details>
<summary>💡 Ver respuesta</summary>

```python
print(portafolio.head())
print(portafolio.shape)
print(portafolio.dtypes)
print(portafolio.describe())
```
</details>

> 💡 **Idea clave** — El método `.describe()` no es un concepto nuevo que debamos memorizar. Combina varias de las funciones ya conocidas de NumPy (`mean`, `std`, `min`, `max`) y las presenta de forma consolidada, columna por columna.

📚 Fuente: ["10 minutes to pandas" — "Viewing data", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#viewing-data)

---
## 04 · Selección de datos

> **Nota** — Objetivo: Extraeremos columnas, filas y subconjuntos específicos de un DataFrame.

| Sintaxis | Qué selecciona |
|---|---|
| `portafolio["ticker"]` | una sola columna (Series) |
| `portafolio[["ticker", "cantidad"]]` | varias columnas (DataFrame) |
| `portafolio.loc[0]` | una fila, por su etiqueta |
| `portafolio.iloc[0]` | una fila, por su posición |

In [18]:
print(portafolio["ticker"])
print(portafolio.loc[0])

0     AAPL
1     MSFT
2     AMZN
3    GOOGL
Name: ticker, dtype: object
ticker           AAPL
cantidad           10
precio_compra     180
precio_actual     195
Name: 0, dtype: object

**✏️ Completa el código** — Filtraremos el portafolio para quedarnos solo con los activos cuya `cantidad` sea mayor a 8.

In [25]:
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
muchas_unidades

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
2   AMZN        12            170            185

<details>
<summary>💡 Ver respuesta</summary>

```python
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
```
</details>

> 💡 **Idea clave** — En S13, aprendimos que comparar un array con un número (`ganancia > 0`) produce un array de valores booleanos (verdadero/falso). Este mismo principio aplica al filtrar un DataFrame: `portafolio["cantidad"] > 8` genera una máscara booleana que pandas utiliza para seleccionar solo las filas donde la condición es verdadera.

📚 Fuente: ["10 minutes to pandas" — "Selection", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#selection)

---
## 05 · Operaciones más usadas

> **Nota** — Objetivo: Agregar columnas calculadas y resumir un DataFrame de manera eficiente, sin necesidad de ciclos explícitos.

Agregar una columna nueva es tan simple como asignarla — pandas alinea los valores automáticamente.

**✏️ Ahora, completemos el código**

In [27]:
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())   # promedio
print(portafolio["ganancia"].std())   # desviación estándar
portafolio.sort_values(by="ganancia")

75.0
135.27749258468683

  ticker  cantidad  precio_compra  precio_actual  valor_actual  ganancia
1   MSFT         8            400            385          3080      -120
3  GOOGL         6            150            165           990        90
0   AAPL        10            180            195          1950       150
2   AMZN        12            170            185          2220       180

<details>
<summary>💡 Ver respuesta</summary>

```python
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())
print(portafolio["ganancia"].std())
portafolio.sort_values(by="ganancia")
```
</details>

| Operación | Lo que hace |
|---|---|
| `df["col"] = ...` | crea o reemplaza una columna |
| `df["col"].mean() / .std()` | estadísticas sobre una columna |
| `df.sort_values(by="col")` | ordena las filas según una columna |
| `df[condición]` | filtra filas |

📚 Fuente: ["10 minutes to pandas" — "Operations", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#operations)

---
## 06 · Todo junto: el portafolio como DataFrame

> **Nota** — Objetivo: Integraremos la creación, el cálculo de columnas, el filtrado y la ordenación en un flujo unificado.

In [28]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio_compra": [180, 400, 170, 150],
    "precio_actual": [195, 385, 185, 165]
})

portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])
portafolio["rendimiento"] = (portafolio["ganancia"] / (portafolio["cantidad"] * portafolio["precio_compra"])) * 100

en_perdida = portafolio[portafolio["rendimiento"] < 0]
portafolio.sort_values(by="rendimiento", ascending=False)

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
3,GOOGL,6,150,165,990,90,10.000000
2,AMZN,12,170,185,2220,180,8.823529
0,AAPL,10,180,195,1950,150,8.333333
1,MSFT,8,400,385,3080,-120,-3.750000

**🔎 Pregunta de análisis**

Al comparar este bloque de código con el que desarrollamos en S11-S12 utilizando bucles `for` y diccionarios, podemos observar algunas diferencias significativas. ¿Qué componentes del código anterior han sido eliminados por completo? ¿Qué secciones se han simplificado y cuál es la razón de esta concisión?

---
## 🎯 07 · Reto individual

Retomaremos el portafolio que se nos asignó en el reto de S11-S12.

In [29]:
portafolios = {
    0: {"AAPL": {"cantidad": 10, "precio_compra": 180}, "MSFT": {"cantidad": 8, "precio_compra": 400}, "AMZN": {"cantidad": 12, "precio_compra": 170}, "GOOGL": {"cantidad": 6, "precio_compra": 150}},
    1: {"TSLA": {"cantidad": 15, "precio_compra": 220}, "NVDA": {"cantidad": 20, "precio_compra": 120}, "META": {"cantidad": 10, "precio_compra": 480}, "NFLX": {"cantidad": 5,  "precio_compra": 600}},
    2: {"JPM":  {"cantidad": 25, "precio_compra": 150}, "KO":   {"cantidad": 40, "precio_compra": 60},  "DIS":  {"cantidad": 20, "precio_compra": 95},  "INTC": {"cantidad": 50, "precio_compra": 35}},
    3: {"V":    {"cantidad": 12, "precio_compra": 260}, "PG":   {"cantidad": 18, "precio_compra": 150}, "XOM":  {"cantidad": 30, "precio_compra": 105}, "PFE":  {"cantidad": 60, "precio_compra": 30}},
    4: {"AMD":  {"cantidad": 22, "precio_compra": 140}, "CSCO": {"cantidad": 35, "precio_compra": 50},  "IBM":  {"cantidad": 10, "precio_compra": 190}, "ORCL": {"cantidad": 15, "precio_compra": 130}},
    5: {"BA":   {"cantidad": 8,  "precio_compra": 210}, "CAT":  {"cantidad": 10, "precio_compra": 320}, "MMM":  {"cantidad": 20, "precio_compra": 100}, "GE":   {"cantidad": 25, "precio_compra": 160}},
    6: {"WMT":  {"cantidad": 15, "precio_compra": 65},  "HD":   {"cantidad": 8,  "precio_compra": 340}, "NKE":  {"cantidad": 30, "precio_compra": 90},  "MCD":  {"cantidad": 10, "precio_compra": 280}},
    7: {"T":    {"cantidad": 60, "precio_compra": 18},  "VZ":   {"cantidad": 40, "precio_compra": 40},  "CVX":  {"cantidad": 12, "precio_compra": 150}, "JNJ":  {"cantidad": 15, "precio_compra": 160}},
}
precios_actuales_todos = {
    0: {"AAPL": 195, "MSFT": 385, "AMZN": 185, "GOOGL": 165},
    1: {"TSLA": 250, "NVDA": 135, "META": 460, "NFLX": 640},
    2: {"JPM": 165, "KO": 58, "DIS": 100, "INTC": 28},
    3: {"V": 280, "PG": 155, "XOM": 115, "PFE": 26},
    4: {"AMD": 160, "CSCO": 48, "IBM": 210, "ORCL": 145},
    5: {"BA": 195, "CAT": 350, "MMM": 95, "GE": 180},
    6: {"WMT": 70, "HD": 360, "NKE": 78, "MCD": 295},
    7: {"T": 20, "VZ": 38, "CVX": 165, "JNJ": 172},
}

# 👉 Reemplaza con tu código de estudiante (solo números)
mi_codigo_estudiante = 1007918888

grupo = mi_codigo_estudiante % 8
mi_portafolio_dict = portafolios[grupo]
mis_precios_dict = precios_actuales_todos[grupo]

print(f"Tu portafolio asignado (grupo {grupo}):")
print(mi_portafolio_dict)

Tu portafolio asignado (grupo 0):
{'AAPL': {'cantidad': 10, 'precio_compra': 180}, 'MSFT': {'cantidad': 8, 'precio_compra': 400}, 'AMZN': {'cantidad': 12, 'precio_compra': 170}, 'GOOGL': {'cantidad': 6, 'precio_compra': 150}}

### Nuestra tarea

Utilizando `mi_portafolio_dict` y `mis_precios_dict`:

1. Construir un DataFrame con las columnas `ticker`, `cantidad`, `precio_compra`, `precio_actual`.
2. Agregar las columnas `valor_actual`, `ganancia` y `rendimiento`.
3. Filtrar los activos en pérdida.
4. Ordenar el DataFrame de mayor a menor rendimiento.

In [ ]:
# ✏️ Aquí insertaremos nuestro código — podemos usar las secciones 03-06 como referencia, ya que no hay una plantilla específica.

### 1. Construir un DataFrame con las columnas `ticker`, `cantidad`, `precio_compra`, `precio_actual`.

Para iniciar, transformaremos los datos de `mi_portafolio_dict` y `mis_precios_dict` a un formato adecuado para un DataFrame. Primero, los unificaremos en una lista de diccionarios, donde cada diccionario corresponderá a una fila en nuestro DataFrame.

In [30]:
import pandas as pd

# Prepara los datos para el DataFrame
# Iteramos sobre los ítems del diccionario de portafolio para construir una lista de diccionarios.
# Cada diccionario contendrá 'ticker', 'cantidad', 'precio_compra' y 'precio_actual'.

datos_portafolio = []
for ticker, detalles in mi_portafolio_dict.items():
    datos_portafolio.append({
        "ticker": ticker,
        "cantidad": detalles["cantidad"],
        "precio_compra": detalles["precio_compra"],
        "precio_actual": mis_precios_dict[ticker]
    })

# Crea el DataFrame
portafolio_df = pd.DataFrame(datos_portafolio)
display(portafolio_df.round(2))

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
1   MSFT         8            400            385
2   AMZN        12            170            185
3  GOOGL         6            150            165

### 2. Agregar las columnas `valor_actual`, `ganancia` y `rendimiento`.

Ahora, procederemos a calcular las nuevas columnas. Para ello, utilizaremos las operaciones vectorizadas de pandas, que destacan por su eficiencia y eliminan la necesidad de emplear bucles `for` explícitos.

In [31]:
# Calcula el valor actual de cada posición
portafolio_df["valor_actual"] = portafolio_df["cantidad"] * portafolio_df["precio_actual"]

# Calcula la ganancia (o pérdida) de cada posición
portafolio_df["ganancia"] = portafolio_df["valor_actual"] - (portafolio_df["cantidad"] * portafolio_df["precio_compra"])

# Calcula el rendimiento porcentual
# Asegúrate de no dividir por cero si el precio_compra * cantidad podría ser 0
portafolio_df["rendimiento"] = (portafolio_df["ganancia"] / (portafolio_df["cantidad"] * portafolio_df["precio_compra"])) * 100

display(portafolio_df.round(2))

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
0,AAPL,10,180,195,1950,150,8.33
1,MSFT,8,400,385,3080,-120,-3.75
2,AMZN,12,170,185,2220,180,8.82
3,GOOGL,6,150,165,990,90,10.00

### 3. Filtrar los activos en pérdida.

Para identificar los activos con rendimiento negativo, aplicaremos una condición de filtrado al DataFrame.

In [32]:
# Filtra el DataFrame para mostrar solo los activos con rendimiento negativo
activos_en_perdida = portafolio_df[portafolio_df["rendimiento"] < 0]
display(activos_en_perdida.round(2))

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
1,MSFT,8,400,385,3080,-120,-3.75

### 4. Ordenar el DataFrame de mayor a menor rendimiento.

Finalmente, ordenaremos el portafolio completo en función de la columna `rendimiento`, de forma descendente.

In [33]:
# Ordena el DataFrame completo por la columna 'rendimiento' de mayor a menor
portafolio_ordenado = portafolio_df.sort_values(by="rendimiento", ascending=False)
display(portafolio_ordenado.round(2))

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
3,GOOGL,6,150,165,990,90,10.00
2,AMZN,12,170,185,2220,180,8.82
0,AAPL,10,180,195,1950,150,8.33
1,MSFT,8,400,385,3080,-120,-3.75

### Exit ticket: Pregunta de análisis


«Nuestro portafolio, ordenado de mayor a menor rendimiento, tiene a **GOOGL** primero y a **MSFT** último. **1** activo(s) está(n) en pérdida.»

### Exit ticket

«Nuestro portafolio, ordenado de mayor a menor rendimiento, tiene a **___** primero y a **___** último. **___** activos están en pérdida.»

---

📚 **Fuentes** · ["10 minutes to pandas"](https://pandas.pydata.org/docs/user_guide/10min.html) · ["Package overview"](https://pandas.pydata.org/docs/getting_started/overview.html)